Test CockroachDB

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -74,6 +74,27 @@ jobs:
         echo PGPORT=6432 'PQTEST_BINARY_PARAMETERS=yes go test -race ./...'
         PGPORT=6432 PQTEST_BINARY_PARAMETERS=yes go test -race ./...
 
+  cockroach:
+    runs-on: 'ubuntu-latest'
+    steps:
+    - uses: 'actions/checkout@v6'
+    - uses: 'actions/setup-go@v6'
+      with: {go-version: '1.26'}
+    - name: 'Start CockroachDB'
+      run: |
+        docker compose up cockroach -d --wait || {
+          docker compose logs
+          exit 1
+        }
+        echo '127.0.0.1 postgres postgres-invalid' | sudo tee -a /etc/hosts
+    - name: 'Run tests'
+      run: |
+        echo 'PGPORT=26257 PQTEST_BINARY_PARAMETERS=no  go test -race -skip='^Example' ./...'
+        PGPORT=26257 PQTEST_BINARY_PARAMETERS=no  go test -race -skip='^Example' ./...
+
+        echo PGPORT=26257 'PQTEST_BINARY_PARAMETERS=yes go test -race -skip='^Example' ./...'
+        PGPORT=26257 PQTEST_BINARY_PARAMETERS=yes go test -race -skip='^Example' ./...
+
   # Disabled for now as it's kind of finecky and flaky.
   #pgpool:
   #  runs-on: 'ubuntu-latest'
